version: '3.8'

services:
  pizzahub.api:
    container_name: pizzahub.api
    image: pizzahub.api
    build:
      context: .
      dockerfile: Source/Common/PizzaHub.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pizzahub-network
    restart: always
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: TB_Test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bG9jYWxob3N0
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  pizzahub-network:
    driver: bridge
